### ISSUE TITLE
So sorry to reach out through here!

### ISSUE THREAD

**Issue by smeezy0** [yjg30737/pyqt-image-to-text#1]
Unfortunately github doesn't have messages so I hope this is okay.

I am looking for anyone who has shown recent interest in PyQt5.

Me and a small group of others are working on a productivity tool using PyQt5. Our goal is to create a tool that can help others in any industry. Specifically we are creating a feature heavy productivity tool. I think this could be a good opportunity to add on to your portfolio, learn something new and work in a team setting. We need any help we can get :)

https://github.com/derto42/FlowBuddy

Please add the discord if interested: https://discord.gg/ahvpBbXG

**Comment by yjg30737** [comment]
I'm not sure i can be helpful in this project, since i've never particiapted in any of team projects in GitHub (doesn't count my company project which is using GitLab)

But i can give it a shot at least participating in Discord server and find out what's going on there :)
